### ISSUE TITLE
Add test to help ensure that range requests get a 302, not an error code

### ISSUE THREAD

**Issue by stephendonner** [mozilla/bouncer-tests#73]
We found what we think is an issue with CloudFront handling the caching/requests, when we deployed the migrated Bouncer in AWS.  In particular, the -r 4000000-4200000 portion caused many HTTP 416 errors, as shown below, which we'd like to catch through automation.

Without getting too tricky, can we do the equivalent of this curl command, and check/assert that the return code is a 302?

Here's the FAILURE/ERROR case/response:

10-22-248-50:~ sdonner$ curl -v -r 4000000-4200000  http://download.mozilla.org/\?product\=firefox-41.0.2-partial-41.0.1\&os\=win\&lang\=es-ES
*   Trying 54.230.205.227...
* Connected to download.mozilla.org (54.230.205.227) port 80 (#0)
> GET /?product=firefox-41.0.2-partial-41.0.1&os=win&lang=es-ES HTTP/1.1
> Host: download.mozilla.org
> Range: bytes=4000000-4200000
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 416 Requested Range Not Satisfiable
< Content-Type: text/html
< Content-Length: 49
< Connection: keep-alive
< Server: CloudFront
< Date: Thu, 15 Oct 2015 22:03:40 GMT
< Expires: Thu, 15 Oct 2015 22:03:40 GMT
< X-Cache: Error from cloudfront
< Via: 1.1 f3b0d220628b01da1f767768364a12cc.cloudfront.net (CloudFront)
< X-Amz-Cf-Id: W3-af-xyPxD7cDeeuZe5oGETvBL6dyCCwCEd7Gp-3qlDuac843aPTg==
< 
<html><body>Sorry, invalid request</body></html>
* Connection #0 to host download.mozilla.org left intact

Below is the SUCCESS case:

10-22-248-50:~ sdonner$ curl -v -r 4000000-4200000  http://download.mozilla.org/\?product\=firefox-41.0.2-partial-41.0.1\&os\=win\&lang\=es-ES
*   Trying 54.210.180.137...
* Connected to download.mozilla.org (54.210.180.137) port 80 (#0)
> GET /?product=firefox-41.0.2-partial-41.0.1&os=win&lang=es-ES HTTP/1.1
> Host: download.mozilla.org
> Range: bytes=4000000-4200000
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 302 Found
< Cache-Control: max-age=60
< Content-Type: text/html; charset=utf-8
< Date: Thu, 15 Oct 2015 22:27:04 GMT
< Location: http://download.cdn.mozilla.net/pub/firefox/releases/41.0.2/update/win32/es-ES/firefox-41.0.1-41.0.2.partial.mar
< Content-Length: 135
< Connection: keep-alive
< 
<a href="http://download.cdn.mozilla.net/pub/firefox/releases/41.0.2/update/win32/es-ES/firefox-41.0.1-41.0.2.partial.mar">Found</a>.

* Connection #0 to host download.mozilla.org left intact

**Comment by m8ttyB** [comment]
Thanks @stephendonner, this is great! Hadn't thought to explore the usage of the `-r` flag before. A question to help clarify what's going on, why the choice to use this range, `-r 4000000-4200000`?

**Comment by rail** [comment]
@catlee has this snippet of code: https://gist.github.com/catlee/a5d47b0b990346220365
"it fails with different ranges, depending on chunk size, e.g., with block_size 300000, it fails at 1200000-1500000"

**Comment by m8ttyB** [comment]
Closing this out. Haven't seen this issue in quite some time.
