### ISSUE TITLE
Don't log jenkins notices to #sync

### ISSUE THREAD

**Issue by rfk** [mozilla/bouncer-tests#74]
Hi!  It looks like there's a jenkins job for this repo, that logs success/failure messages into both #services-dev and #sync in IRC.  Can you please reconfigure it to only log to #services-dev which is a lower-volumne channel?

**Comment by davehunt** [comment]
I'm guessing this is from https://ci.mozilla.org/view/Bouncer/ as the jobs at https://webqa-ci.mozilla.com/view/Bouncer/ only notify #stubby and #mozwebqa on status change. As far as I can see, the ci.mozilla.org jobs are configured to notify changes to all channels configured at the global level in Jenkins. I do not have the necessary authorization to see or modify the list of channels. I could change the job to notify to just #services-dev as requested, but unless this channel is already configured in the global settings, this would effectively just silence the bot entirely. @stephendonner do you know who has the necessarily authorization to make global settings changes on ci.mozilla.org?

**Comment by davehunt** [comment]
I'm pretty sure nothing's changed here recently, except maybe that the Bouncer tests are hitting failures much more frequently.

**Comment by rfk** [comment]
The Jenkins metadata on that project suggests @m8ttyB as the owner; Matt can you help out with this?

**Comment by stephendonner** [comment]
I wish I could help, but 302 -> @fox2mike or @superawesome ; when I hit up https://ci.mozilla.org/manage I get "Access Denied \n sdonner@mozilla.com is missing the Overall/Administer permission."

**Comment by davehunt** [comment]
https://ci.mozilla.org is :skull: you won't be hearing anything more from it :smiling_imp:
