### ISSUE TITLE
Up timeout to 300 seconds

### ISSUE THREAD

**Issue by m8ttyB** [mozilla/bouncer-tests#84]
We're exploring the shape of what is causing the tests to sporadically fail due to timeouts. It's been suggested that this may be due to how the squid proxy is configured to timeout a request after [300 seconds](https://bugzilla.mozilla.org/show_bug.cgi?id=1244851).

Task:

* up the requests timeout to 300
* observe if the behavior of the jobs for bouncer.prod and bouncer.stage changes
* report back to the bug

**Comment by m8ttyB** [comment]
Let's not close this task yet. I want the tests to have a chance to run over night so we can gather additional data points. As it stands, changing the timeout has "fixed" the tests.

I have a 2nd set of tests running outside of our Jenkins env [here](https://ci.us-west.moz.works/view/mbrandt-bouncer/) to gather additional reference points.

**Comment by davehunt** [comment]
From the bug:

> Squid defaults:
> connect_timeout 60s
> request_timeout 300s

By setting the bouncer tests to timeout at 300 seconds, I think there's still a chance you'll get the test timing out and not the proxy timeout message. In [bug 1238977](https://bugzilla.mozilla.org/show_bug.cgi?id=1238977) I've seen proxy timeouts after 15 minutes. Also, the bouncer tests run every 5 minutes, so there's a chance will stack up jobs if a timeouts occur.

**Comment by davehunt** [comment]
I suspect this can be closed now, @m8ttyB?

**Comment by m8ttyB** [comment]
yep
